name: repomd
on:
  push:
  workflow_dispatch:
  schedule:
  - cron:  '25 0,6,12,18 * * *'

jobs:
  repomd:
    runs-on: ubuntu-20.04
    env:
      DO_SPACE_NAME: 'ns8'
      DO_SPACE_REGION: 'ams3'
      CDN_DOMAIN: 'distfeed.nethserver.org'
    steps:
    - id: checkout
      uses: actions/checkout@v3

    - id: buildmd
      run: |
        bash createrepo.sh
        rm -rf README.md createrepo.py createrepo.sh .git .github

    - id: publish
      name: "Publish the repository metadata"
      uses: BetaHuhn/do-spaces-action@v2
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        access_key: ${{ secrets.DO_SPACE_ACCESS_KEY }}
        secret_key: ${{ secrets.DO_SPACE_SECRET_KEY }}
        space_name: ${{ env.DO_SPACE_NAME }}
        space_region: ${{ env.DO_SPACE_REGION }}
        cdn_domain: ${{ env.CDN_DOMAIN }}
        source: .
        out_dir: ns8/updates/
